Update App.js
lab49gittesters/github-vs-gitlab pull request #4
Opened 2019-03-28 15:30 UTC by anotherFeng2

2019-03-28 18:23 UTC, anotherFeng commented
@lab49gittesters

2019-03-29 13:58 UTC, anotherFeng requested changes
Change p tag to div.

2019-03-29 13:58 UTC, anotherFeng commented on src/App.js
> +            Hello World
This is a much better idea!

2019-03-29 14:29 UTC, anotherFeng2 commented on src/App.js
> +            Hello World
No can't do.

2019-03-29 14:44 UTC, closed without merging